package org.mystore.dto;

import com.fasterxml.jackson.annotation.JsonRootName;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.validation.constraints.Email;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotEmpty;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import lombok.Getter;
import lombok.Setter;
import lombok.experimental.Accessors;
import org.mystore.dto.user.AssociatedSubsitesDto;
import org.mystore.enums.Status;
import org.mystore.enums.user.UserType;

@Getter
@Setter
@JsonRootName("User")
@Accessors(chain = true)
public class UserDto {

    private String userId;
    private String profileId;
    private String title;
    private String firstName;
    private String middleName;
    private String lastName;
    private String fullName;
    private String roleId;
    @Email
    @NotBlank
    private String email;
    private String phoneCode;
    private String phone;
    private String userName;
    private String password;
    private Boolean isLocked;
    private Integer passwordAttempt;
    private String confirmPassword;
    private String newPassword;
    private String givenPassword;
    private List<String> roleOrganizationIds;
    private List<RoleOrganizationResponseDto> roleOrganizations;
    @NotEmpty
    private String defaultOrganizationId;
    private List<String> organizationIds;
    private Boolean isFirstTimeLogin;
    private Boolean isDefaultUser;
    private Boolean isPasswordAutoGenerated;
    private Boolean isOtpEnabled;
    private String resetPasswordToken;
    private Boolean isActive;
    @Enumerated(EnumType.STRING)
    private Status status;
    private UserType userType;
    private Boolean isDeleted;
    private Set<AssociatedSubsitesDto> associatedSubsites = new HashSet<>();

}
